[versions]
agp = "8.9.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
navigationFragment = "2.6.0"
navigationUi = "2.6.0"
circleimageview = "3.1.0"
cardview = "1.0.0"
mpandroidChart = "v3.1.0"
roomCompilerProcessingTesting = "2.8.4"
[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
circleimageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleimageview" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
mpandroidChart = { group = "com.github.PhilJay", name = "mpandroidChart", version.ref = "mpandroidChart" }
amap3d = {group = "com.amap.api", name = "3dmap-location-search", version = "latest.integration"}
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version = "4.12.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

